FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Worker/PlantBasedPizza.Delivery.Worker.csproj
# Build and publish a release
RUN dotnet publish PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Worker/PlantBasedPizza.Delivery.Worker.csproj -c Release -o out -r linux-x64

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "PlantBasedPizza.Delivery.Worker.dll"]