FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /App

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore PlantBasedPizza.Kitchen/application/PlantBasedPizza.Kitchen.ACL/PlantBasedPizza.Kitchen.ACL.csproj
# Build and publish a release
RUN dotnet publish PlantBasedPizza.Kitchen/application/PlantBasedPizza.Kitchen.ACL/PlantBasedPizza.Kitchen.ACL.csproj -c Release -o out -r linux-x64

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0-noble-chiseled as runtime
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "PlantBasedPizza.Kitchen.ACL.dll"]