FROM mcr.microsoft.com/dotnet/sdk:9.0 as build

WORKDIR /App
COPY . ./
RUN dotnet restore PlantBasedPizza.Recipes/applications/PlantBasedPizza.Recipes.Api/PlantBasedPizza.Recipes.Api.csproj
RUN dotnet publish PlantBasedPizza.Recipes/applications/PlantBasedPizza.Recipes.Api/PlantBasedPizza.Recipes.Api.csproj -o out -c Release -r linux-x64

FROM mcr.microsoft.com/dotnet/aspnet:9.0 as runtime
WORKDIR /App
COPY --from=build /App/out .
EXPOSE 80
ENTRYPOINT [ "dotnet", "PlantBasedPizza.Recipes.Api.dll" ]