version: "3.7"
services:
  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

  local.loyalty-api:
    image: ${REGISTRY}/loyalty-api:${IMAGE_TAG}
    depends_on:
      - rabbitmq
    ports:
      - "5271:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__HostName=rabbitmq
      - Messaging__ExchangeName=dev.loyalty
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'

  local.loyalty-internal-api:
    image: ${REGISTRY}/loyalty-internal-api:${IMAGE_TAG}
    ports:
      - "5069:8080"
    depends_on:
      - rabbitmq
      - mongodb
      - jaeger
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__HostName=rabbitmq
      - Messaging__ExchangeName=dev.loyalty

  local.loyalty-worker:
    image: ${REGISTRY}/loyalty-worker:${IMAGE_TAG}
    depends_on:
      - rabbitmq
      - mongodb
      - jaeger
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - ServiceDiscovery__MyUrl=
      - ServiceDiscovery__ServiceName=
      - ServiceDiscovery__ConsulServiceEndpoint=http://consul:8500
      - Messaging__HostName=rabbitmq
      - Messaging__ExchangeName=dev.loyalty