services:
  local.loyalty-api:
    image: loyalty-api
    container_name: local.loyalty-api
    ports:
      - "5271:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'
      - DAPR_HOST=host.docker.internal
      - DAPR_GRPC_PORT=5101

  loyaltyapi-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "loyalty",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components"
    depends_on:
      - "local.loyalty-api"

    network_mode: "service:local.loyalty-api"

  local.loyalty-internal-api:
    image: loyalty-internal-api
    container_name: local.loyalty-internal-api
    ports:
      - "5069:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - DAPR_HOST=host.docker.internal
      - DAPR_GRPC_PORT=5101

  loyaltyinternal-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "loyaltyinternal",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
        "--app-protocol",
        "grpc",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.loyalty-internal-api"

    network_mode: "service:local.loyalty-internal-api"

  local.loyalty-worker:
    image: loyalty-worker
    container_name: local.loyalty-worker
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - DAPR_HOST=host.docker.internal
      - DAPR_GRPC_PORT=5101

  loyaltyworker-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "loyaltyworker",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.loyalty-worker"
    network_mode: "service:local.loyalty-worker"
    
  integration-test-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id",
      "integration-tests",
      "--placement-host-address",
      "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--dapr-grpc-port",
      "5101",
      "--resources-path",
      "./components",
    ]
    ports:
      - "5101:5101"
    volumes:
      - "./components/:/components"