FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /App
COPY . ./
RUN dotnet restore PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Api/PlantBasedPizza.Delivery.Api.csproj
RUN dotnet publish PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Api/PlantBasedPizza.Delivery.Api.csproj -o out -c Release -r linux-x64

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime
WORKDIR /App
COPY --from=build /App/out .
EXPOSE 80
ENTRYPOINT [ "dotnet", "PlantBasedPizza.Delivery.Api.dll" ]