@HostAddress = http://localhost:5139

POST {{HostAddress}}/account/register
Accept: application/json
Content-Type: application/json

{
  "emailAddress": "test@test.com",
  "password": "thisisanewpassword"
}

###

POST {{HostAddress}}/account/login
Accept: application/json
Content-Type: application/json

{
  "emailAddress": "test@test.com",
  "password": "thisisanewpassword"
}

###
