services:
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16686:16686"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"