version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318
  
  cache:
    image: redis:7.2
    ports:
      - '6379:6379'

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - 8443:8080
    volumes:
      - ./mocks/loyalty-api:/home/wiremock

  gripmock:
    image: tkpd/gripmock:latest
    ports:
      - 4770:4770
      - 4771:4771
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/loyalty.proto /proto/payment.proto

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672