services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "27017:27017"
    networks:
      - dapr

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - "16686:16686"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
    networks:
      - dapr
  
  cache:
    image: redis:7.2
    ports:
      - "6379:6379"
    networks:
      - dapr

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./mocks/loyalty-api:/home/wiremock
    networks:
      - dapr

  loyalty-gripmock:
    image: tkpd/gripmock:latest
    ports:
      - "8081:4770"
      - "8082:4771"
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/loyalty.proto
    networks:
      - dapr

  payment-gripmock:
    image: tkpd/gripmock:latest
    ports:
      - "8083:4770"
      - "8084:4771"
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/payment.proto
    networks:
      - dapr

  integration-test-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id",
      "integration-tests",
      "--placement-host-address",
      "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--dapr-grpc-port",
      "5101",
      "--resources-path",
      "../../components",
    ]
    ports:
      - "5101:5101"
    volumes:
      - "../../components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    networks:
      - dapr

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr

networks:
  dapr: null