version: "3.7"
services:
  local.kitchen-api:
    image: kitchen-api
    ports:
      - "5097:8080"
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017 
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - REDIS_CONNECTION_STRING=cache:6379
      - CACHE_NAME=kitchen
      - Environment=local
      - Services__Recipes=recipes
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'

  kitchen-api-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "kitchen",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.kitchen-api"
    network_mode: "service:local.kitchen-api"

  local.kitchen-worker:
    image: kitchen-worker
    restart: on-failure
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - REDIS_CONNECTION_STRING=cache:6379
      - CACHE_NAME=kitchen
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - Environment=local
      - Services__Recipes=recipes
      - Services__OrdersInternal=http://orders-gripmock:4770

  kitchen-worker-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "kitchen-worker",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.kitchen-worker"
    network_mode: "service:local.kitchen-worker"
    
  integration-test-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id",
      "integration-tests",
      "--placement-host-address",
      "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--dapr-grpc-port",
      "5101",
      "--resources-path",
      "./components",
    ]
    ports:
      - "5101:5101"
    volumes:
      - "./components/:/components"