version: "3.7"
services:
  mongodb:
    image: mongo
    container_name: kitchen-mongodb
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 16686:16686
      - 13133:13133
      - 4317:4317
      - 4318:4318
  
  cache:
    image: redis:7.2
    ports:
      - '6379:6379'

  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - 8443:8080
    volumes:
      - ./mocks/recipe-api:/home/wiremock

  wiremock-recipes-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "recipes",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "wiremock"
    network_mode: "service:wiremock"

  orders-gripmock:
    image: tkpd/gripmock:latest
    ports:
      - "8083:4770"
      - "8084:4771"
    volumes:
      - ./mocks/grpc-mocks:/proto
    command: --stub=/proto/stubs /proto/orders.proto

  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr:1.14.4"
    command: ["./placement", "-port", "50005"]
    ports:
      - "50005:50005"
      - "8070:58080"
      - "9090:59090"

  ############################
  # Dapr scheduler service
  ############################
  scheduler:
    image: "daprio/dapr:1.14.4"
    command: ["./scheduler", "--port", "50006", "--etcd-data-dir", "/var/lock"]
    ports:
      - "50006:50006"
      - "2379:52379"
      - "8071:58081"
      - "9091:59091"
    volumes:
      - "/var/lock"