name: Kitchen Services CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-kitchen-services.yaml
        - src/PlantBasedPizza.Kitchen/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-api-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      image-name: kitchen-api
      dockerfile: src/PlantBasedPizza.Kitchen/application/PlantBasedPizza.Kitchen.Api/Dockerfile-x86
      docker-repository: plantpowerjames/plant-based-pizza-kitchen-api
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  build-worker-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      image-name: kitchen-worker
      dockerfile: src/PlantBasedPizza.Kitchen/application/PlantBasedPizza.Kitchen.Worker/Dockerfile-x86
      docker-repository: plantpowerjames/plant-based-pizza-kitchen-worker
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}