name: Recipe API CICD

on:
  push:
    branches:
      - feat/dapr
    paths:
      - .github/workflows/build-base.yaml
      - .github/workflows/integration-test-base.yaml
      - .github/workflows/build-recipe-services.yaml
      - src/PlantBasedPizza.Recipes/**
      - src/shared/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      docker-repository: plantpowerjames/plant-based-pizza-recipe-api
      image-name: recipe-api
      dockerfile: src/PlantBasedPizza.Recipes/applications/PlantBasedPizza.Recipes.Api/Dockerfile-x86
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
