name: Account Services CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-account-services.yaml
        - src/PlantBasedPizza.Account/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-make.yaml@feat/dapr
    with:
      application-root-folder: ./src/PlantBasedPizza.Account/
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}