name: Recipe API CICD

on:
  push:
    branches:
      - feat/dapr
    paths:
      - .github/workflows/build-base.yaml
      - .github/workflows/integration-test-base.yaml
      - .github/workflows/build-recipe-services.yaml
      - src/PlantBasedPizza.Recipes/**
      - src/shared/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      application-root-folder: ./src/PlantBasedPizza.Recipes/
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
