name: Account Services CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-account-services.yaml
        - src/PlantBasedPizza.Account/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      image-name: account-api
      dockerfile: src/PlantBasedPizza.Account/application/PlantBasedPizza.Account.Api/Dockerfile-x86
      docker-repository: plantpowerjames/plant-based-pizza-account-api
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}