name: Build & Push Base Workflow

on:
  workflow_call:
    inputs:
      image-name:
          required: true
          type: string
      docker-repository:
          required: true
          type: string
      dockerfile:
          required: true
          type: string
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Dockerhub username to login with'
        required: true
      DOCKERHUB_TOKEN:
          description: 'The Dockerhub token'
          required: true

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      -
        name: Build local image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          tags: ${{ inputs.image-name }}:latest
          context: ./src
          file: ${{ inputs.dockerfile }}
      - name: Tag With Commit Hash
        run: docker tag ${{inputs.image-name}} ${{inputs.docker-repository}}:${{ env.sha_short }}
      - name: Push to DockerHub
        run: docker push ${{inputs.docker-repository}}:${{ env.sha_short }}
          