name: Build & Push Base Workflow

on:
  workflow_call:
    inputs:
      application-root-folder:
          type: string
          required: true
    secrets:
      DOCKERHUB_USERNAME:
        description: 'The Dockerhub username to login with'
        required: true
      DOCKERHUB_TOKEN:
          description: 'The Dockerhub token'
          required: true

permissions:
  id-token: write
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'

      - name: Run unit tests
        run: |
          cd ${{inputs.application-root-folder}};make unit-test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Declare some variables
        shell: bash
        run: |
          echo "IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Build images
        run: |
          cd ${{inputs.application-root-folder}};make build
      - name: Run Integration Tests
        run: |
          cd ${{inputs.application-root-folder}};docker compose -f docker-compose-integration.yml;make integration-test
      - name: Tag With Commit Hash
        run: cd ${{inputs.application-root-folder}};make tag-images
      - name: Push to DockerHub
        run: cd ${{inputs.application-root-folder}};make push
          