name: Order Services CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-order-services.yaml
        - src/PlantBasedPizza.Orders/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-api-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      docker-repository: plantpowerjames/plant-based-pizza-order-api
      image-name: orders-api
      dockerfile: src/PlantBasedPizza.Orders/application/PlantBasedPizza.Orders.Api/Dockerfile-x86
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}

  build-worker-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      docker-repository: plantpowerjames/plant-based-pizza-orders-worker
      image-name: orders-worker
      dockerfile: src/PlantBasedPizza.Orders/application/PlantBasedPizza.Orders.Worker/Dockerfile-x86
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}