name: Recipe API CICD

on:
  push:
    branches:
      - azure
    paths:
      - .github/workflows/build-base.yaml
      - .github/workflows/integration-test-base.yaml
      - .github/workflows/build-recipe-services.yaml
      - src/PlantBasedPizza.Recipes/**
      - src/shared/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  static-analysis:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/static-analysis.yaml@azure
    with:
      service-name: recipes
      directory: ./src/PlantBasedPizza.Recipes/
    secrets:
      dd_api_key: ${{secrets.ACA_DD_API_KEY}}
      dd_app_key: ${{secrets.ACA_DD_APP_KEY}}
  build-and-push:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@azure
    needs: static-analysis
    with:
      application-root-folder: ./src/PlantBasedPizza.Recipes/
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
      DD_API_KEY: ${{secrets.ACA_DD_API_KEY}}
