name: Delivery Services CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-delivery-services.yaml
        - src/PlantBasedPizza.Delivery/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-api-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      image-name: delivery-api
      dockerfile: src/PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Api/Dockerfile-x86
      docker-repository: plantpowerjames/plant-based-pizza-delivery-api
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  build-worker-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      image-name: delivery-worker
      dockerfile: src/PlantBasedPizza.Delivery/application/PlantBasedPizza.Delivery.Worker/Dockerfile-x86
      docker-repository: plantpowerjames/plant-based-pizza-delivery-worker
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}