name: Payment API CICD

on:
    push:
      branches:
        - feat/dapr
      paths:
        - .github/workflows/build-and-push-base.yaml
        - .github/workflows/build-payment-services.yaml
        - src/PlantBasedPizza.Payments/**
        - src/shared/**
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/build-and-push-base.yaml@feat/dapr
    with:
      docker-repository: plantpowerjames/plant-based-pizza-payment-api
      image-name: payment-api
      dockerfile: src/PlantBasedPizza.Payments/application/PlantBasedPizza.Payments/Dockerfile-x86
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}