name: Deploy Shared Infra

on:
  push:
    branches:
      - azure
    paths:
      - .github/workflows/depoloy-shared-infra.yaml
      - infra/environment/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/tf-deploy-base.yaml@azure
    with:
      infrastructure-root-folder: "./infra/environment"
      tf-state-backend-key: plantbasedpizza.tfstate
      resource-group-name: plant-based-pizza-dev
      env: dev
      public-service-bus-namespace: plant-based-pizza-pub-dev
      additional-arguments: " -var temporal_db_user_name=\"\" --var temporal_db_password=\"\""
    secrets:
      AZURE_CLIENT_ID: ${{secrets.DEV_AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      DD_API_KEY: ${{secrets.ACA_DD_API_KEY}}
      DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
      MOMENTO_API_KEY: ${{secrets.MOMENTO_API_KEY}}
