name: Loyalty Services CICD

on:
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  teardown-dev:
    uses: jeastham1993/PlantBasedPizza/.github/workflows/tf-teardown.yaml@azure
    with:
      infrastructure-root-folder: "./infra/loyalty"
      tf-state-backend-key: loyalty.tfstate
      resource-group-name: plant-based-pizza-dev
      env: dev
      public-service-bus-namespace: plant-based-pizza-pub-dev
    secrets:
      AZURE_CLIENT_ID: ${{secrets.DEV_AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      DD_API_KEY: ${{secrets.ACA_DD_API_KEY}}
      DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
      MOMENTO_API_KEY: ${{secrets.MOMENTO_API_KEY}}