name: TF Deploy Sample
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.PAYMENTS_AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  MOMENTO_API_KEY: ${{secrets.MOMENTO_API_KEY}}
  DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
  ARM_USE_AZUREAD: true
  TF_LOG: INFO

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/payments
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PAYMENTS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=payments-test.tfstate" -backend-config="use_oidc=true"
      - name: Terraform apply
        id: apply
        run: |
            terraform apply -var subscription_id="${AZURE_SUBSCRIPTION_ID}" \
                -var resource_group_name="plant-based-pizza-payments-test" \
                -var env="payments-test" \
                -var app_version="8c33328" \ 
                -var dd_api_key="${DD_API_KEY}" \
                -var dd_site="datadoghq.eu" \
                -var momento_api_key="${MOMENTO_API_KEY}" \
                -var db_connection_string="${DB_CONNECTION_STRING}" \
                -var public_service_bus_namespace="plant-based-pizza-public-payments-test" \
                -auto-approve


        
