services:
  local.delivery-api:
    image: delivery-api
    ports:
      - "5259:8080"
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - REDIS_CONNECTION_STRING=cache:6379
      - CACHE_NAME=delivery
      - Environment=local
      - Auth__Issuer=https://plantbasedpizza.com
      - Auth__Audience=https://plantbasedpizza.com
      - Auth__Key=This is a sample secret key - please don't use in production environment.'
      - DAPR_HOST=host.docker.internal
      - DAPR_GRPC_PORT=5101

  deliver-api-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "delivery",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.delivery-api"
    network_mode: "service:local.delivery-api"

  local.delivery-worker:
    image: delivery-worker
    environment:
      - DatabaseConnection=mongodb://mongodb:27017
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - REDIS_CONNECTION_STRING=cache:6379
      - CACHE_NAME=delivery
      - Environment=local
      - DAPR_HOST=host.docker.internal
      - DAPR_GRPC_PORT=5101

  deliver-worker-dapr:
    image: "daprio/daprd:edge"
    command: [
        "./daprd",
        "--app-id",
        "delivery-worker",
        "--app-port",
        "8080",
        "--placement-host-address",
        "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
        "--dapr-grpc-port",
        "5101",
        "--resources-path",
        "./components",
      ]
    volumes:
      - "./components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - "local.delivery-worker"
    network_mode: "service:local.delivery-worker"
    

  integration-test-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id",
      "integration-tests",
      "--placement-host-address",
      "placement:50006", # Dapr's placement service can be reach via the docker DNS entry
      "--dapr-grpc-port",
      "5101",
      "--resources-path",
      "./components",
    ]
    ports:
      - "5101:5101"
    volumes:
      - "./components/:/components"